// Auto-generated by deploy script — 2026-02-23T03:54:40.049Z
export const DEPLOYED_ADDRESSES: Record<number, Record<string, string>> = {
  80002: {
    "USDC": "0x6a06aeD671156A3C133AAe0EEc7f93f679a3eC4c",
    "StealthAnnouncer": "0x2314F19Bc7Fc8e3cAFEC8D8bC157402b0DF8025C",
    "StealthMetaRegistry": "0x9d0cDD13239b8ce12A8F07e62315aBd96605127a",
    "FeeVault": "0x5e41d2A5F67bCaaf187FFF5E727790e60B93AEe4",
    "AgentRegistry": "0x7F657448444456e8E878f8575822ef7268d6b5e3",
    "ComplianceGate": "0x0C3F48c3e863f13b9F7e1dEF0F77A94a073b2D0F",
    "StealthPaymentRouter": "0x505285860b5ECdAb4aaf1EB822e1c1FFb3836729",
    "CrossChainRouter": "0x8ACB1d549915eE2d5eAcb844d971C58767590833"
},
};

export function getAddresses(chainId: number) {
  return DEPLOYED_ADDRESSES[chainId] || null;
}
